/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaMysqlDB;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nullmonkey
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("travel?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        personQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Person p");
        personList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : personQuery.getResultList();
        tPanels = new javax.swing.JTabbedPane();
        PersonPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TravelArange = new javax.swing.JPanel();
        DetailsPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(644, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tPanels.setPreferredSize(new java.awt.Dimension(400, 300));

        PersonPnl.setPreferredSize(new java.awt.Dimension(585, 288));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("ID-Name-Title");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Just Names");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PersonPnlLayout = new javax.swing.GroupLayout(PersonPnl);
        PersonPnl.setLayout(PersonPnlLayout);
        PersonPnlLayout.setHorizontalGroup(
            PersonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(232, 232, 232))
            .addGroup(PersonPnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        PersonPnlLayout.setVerticalGroup(
            PersonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(PersonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        tPanels.addTab("Person", PersonPnl);

        javax.swing.GroupLayout TravelArangeLayout = new javax.swing.GroupLayout(TravelArange);
        TravelArange.setLayout(TravelArangeLayout);
        TravelArangeLayout.setHorizontalGroup(
            TravelArangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        TravelArangeLayout.setVerticalGroup(
            TravelArangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tPanels.addTab("Travel Arangement", TravelArange);

        javax.swing.GroupLayout DetailsPnlLayout = new javax.swing.GroupLayout(DetailsPnl);
        DetailsPnl.setLayout(DetailsPnlLayout);
        DetailsPnlLayout.setHorizontalGroup(
            DetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        DetailsPnlLayout.setVerticalGroup(
            DetailsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        tPanels.addTab("Details", DetailsPnl);

        getContentPane().add(tPanels, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        // Connection code is in MyConnection.java
        
          PersonDao dao= new PersonDao();
       
            ArrayList< Person> personList=new ArrayList< Person>();
            try {
                    for(Object em:(ArrayList)dao.getAllNames())
                    personList.add(( Person)em);
            } catch (SQLException ex) {
            // Logger.getLogger(this.class.getName()).log(Level.SEVERE, null, ex);
                   }
            DefaultTableModel amod = new DefaultTableModel(); //setting the column name
            Object[] tableColumnNames = new Object[1]; 



            tableColumnNames[0] = "name";


            amod.setColumnIdentifiers(tableColumnNames);
 
    Object[] objects = new Object[1];

        if (personList.size() > 0) {
              for (int i = 0; i < personList.size(); i++)
              {
              Person hashmap = personList.get(i);

                objects[0]=hashmap.getName().toString();
                amod.addRow(objects);
              }   
        this.jTable1.setModel(amod);
        } 
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
               PersonDao dao= new PersonDao();
       
            ArrayList< Person> personList=new ArrayList< Person>();
            try {
                    for(Object em:(ArrayList)dao.getAllPerson())
                    personList.add(( Person)em);
            } catch (SQLException ex) {
            // Logger.getLogger(this.class.getName()).log(Level.SEVERE, null, ex);
                   }
            DefaultTableModel amod = new DefaultTableModel(); //setting the column name
            Object[] tableColumnNames = new Object[3]; 



            tableColumnNames[0] = "Person ID";
            tableColumnNames[1] = "name";
            tableColumnNames[2] = "Job Title";

            amod.setColumnIdentifiers(tableColumnNames);
 
    Object[] objects = new Object[3];

        if (personList.size() > 0) {
              for (int i = 0; i < personList.size(); i++)
              {
              Person hashmap = personList.get(i);
                objects[0]=hashmap.getPersonid().toString();
                objects[2]=hashmap.getJobtitle().toString();
                objects[1]=hashmap.getName().toString();
                amod.addRow(objects);
              }   
        this.jTable1.setModel(amod);
        } 
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
                
        
               PersonDao dao= new PersonDao();
       
            ArrayList< Person> personList=new ArrayList< Person>();
            try {
                    for(Object em:(ArrayList)dao.getAllNames())
                    personList.add(( Person)em);
            } catch (SQLException ex) {
            // Logger.getLogger(this.class.getName()).log(Level.SEVERE, null, ex);
                   }
            DefaultTableModel amod = new DefaultTableModel(); //setting the column name
            Object[] tableColumnNames = new Object[1]; 



            tableColumnNames[0] = "name";


            amod.setColumnIdentifiers(tableColumnNames);
 
    Object[] objects = new Object[1];

        if (personList.size() > 0) {
              for (int i = 0; i < personList.size(); i++)
              {
              Person hashmap = personList.get(i);

                objects[0]=hashmap.getName().toString();
                amod.addRow(objects);
              }   
        this.jTable1.setModel(amod);
        } 
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailsPnl;
    private javax.swing.JPanel PersonPnl;
    private javax.swing.JPanel TravelArange;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<javaMysqlDB.Person> personList;
    private javax.persistence.Query personQuery;
    private javax.swing.JTabbedPane tPanels;
    // End of variables declaration//GEN-END:variables
}
